### @(com.57digital.shulker.generated)
### @generated File (generated via ShulkerScript: <BP> functions/ui/toasts/toasts.js)
scoreboard players add @s toast_tick -1
execute as @s[scores={toast_tick=0}] run function ui/toasts/hide
scoreboard players add @s toast_tick -1
execute as @s[scores={toast_tick=0}] run function ui/toasts/hide
execute as @s[scores={toast_obj_id=1000}] run function ui/toasts/show/id/1000
execute as @s[scores={toast_obj_id=1050}] run function ui/toasts/show/id/1050
execute as @s[scores={toast_obj_id=1052}] run function ui/toasts/show/id/1052
execute as @s[scores={toast_obj_id=1054}] run function ui/toasts/show/id/1054
execute as @s[scores={toast_obj_id=1056}] run function ui/toasts/show/id/1056
execute as @s[scores={toast_obj_id=1100}] run function ui/toasts/show/id/1100
execute as @s[scores={toast_obj_id=1110}] run function ui/toasts/show/id/1110
execute as @s[scores={toast_obj_id=1120}] run function ui/toasts/show/id/1120
execute as @s[scores={toast_obj_id=1130}] run function ui/toasts/show/id/1130
execute as @s[scores={toast_obj_id=1140}] run function ui/toasts/show/id/1140
execute as @s[scores={toast_obj_id=1200}] run function ui/toasts/show/id/1200
execute as @s[scores={toast_obj_id=1202}] run function ui/toasts/show/id/1202
execute as @s[scores={toast_obj_id=1204}] run function ui/toasts/show/id/1204
execute as @s[scores={toast_obj_id=1206}] run function ui/toasts/show/id/1206
execute as @s[scores={toast_obj_id=1208}] run function ui/toasts/show/id/1208
execute as @s[scores={toast_obj_id=1220}] run function ui/toasts/show/id/1220
execute as @s[scores={toast_obj_id=1300}] run function ui/toasts/show/id/1300
execute as @s[scores={toast_obj_id=1310}] run function ui/toasts/show/id/1310
execute as @s[scores={toast_obj_id=1320}] run function ui/toasts/show/id/1320
execute as @s[scores={toast_obj_id=1400}] run function ui/toasts/show/id/1400
execute as @s[scores={toast_obj_id=1410}] run function ui/toasts/show/id/1410
execute as @s[scores={toast_obj_id=1420}] run function ui/toasts/show/id/1420
execute as @s[scores={toast_obj_id=1500}] run function ui/toasts/show/id/1500
execute as @s[scores={toast_obj_id=1510}] run function ui/toasts/show/id/1510
execute as @s[scores={toast_obj_id=1530}] run function ui/toasts/show/id/1530
execute as @s[scores={toast_obj_id=1540}] run function ui/toasts/show/id/1540
execute as @s[scores={toast_obj_id=1600}] run function ui/toasts/show/id/1600
execute as @s[scores={toast_obj_id=1610}] run function ui/toasts/show/id/1610
execute as @s[scores={toast_obj_id=1620}] run function ui/toasts/show/id/1620
execute as @s[scores={toast_obj_id=1700}] run function ui/toasts/show/id/1700
execute as @s[scores={toast_obj_id=1750}] run function ui/toasts/show/id/1750
execute as @s[scores={toast_obj_id=1760}] run function ui/toasts/show/id/1760
execute as @s[scores={toast_obj_id=1770}] run function ui/toasts/show/id/1770
execute as @s[scores={toast_obj_id=1900}] run function ui/toasts/show/id/1900
execute as @s[scores={toast_obj_id=1950}] run function ui/toasts/show/id/1950
execute as @s[scores={toast_obj_id=5100}] run function ui/toasts/show/id/5100
execute as @s[scores={toast_obj_id=5200}] run function ui/toasts/show/id/5200
execute as @s[scores={toast_obj_id=5300}] run function ui/toasts/show/id/5300
execute as @s[scores={toast_obj_id=5400}] run function ui/toasts/show/id/5400