tag @s remove item_april_read
tag @s remove item_april_unread
tag @s remove item_splinter_read
tag @s remove item_splinter_unread
tag @s remove item_menu
tag @s remove item_ninja_star
tag @s remove item_ninja_star_empty
tag @s remove item_ooze_attack
tag @s remove item_ooze_attack_empty
tag @s remove item_ooze_tank
tag @s remove item_skateboard_on
tag @s remove item_skateboard_off
tag @s remove item_quest_item
tag @s remove item_sewer_handle
tag @s remove item_sewer_valve
tag @s remove item_weapon
tag @s remove item_weapon_nunchuk
tag @s remove item_weapon_sai
tag @s remove item_weapon_staff
tag @s remove item_weapon_sword
tag @s remove item_turtle_squad
tag @s remove item_turtle_leo
tag @s remove item_turtle_don
tag @s remove item_turtle_mikey
tag @s remove item_turtle_raph
tag @s remove item_regroup