### Generated! Do not edit (project.js)

tag @s remove did_req_dlg
tag @s remove dlg_combo_guide
tag @s remove dlg_epsel_p0_111
tag @s remove dlg_start_100
tag @s remove dlg_start_200
tag @s remove dlg_start_300
tag @s remove dlg_deny_100
tag @s remove dlg_deny_200
tag @s remove dlg_deny_300
tag @s remove dlg_epsel_p0_000
tag @s remove dlg_epsel_p0_100
tag @s remove dlg_epsel_p0_210
tag @s remove dlg_epsel_p0_221
tag @s remove dlg_epsel_p0_222
tag @s remove dlg_epsel_p1_111
tag @s remove dlg_start_400
tag @s remove dlg_start_500
tag @s remove dlg_start_600
tag @s remove dlg_deny_400
tag @s remove dlg_deny_500
tag @s remove dlg_deny_600
tag @s remove dlg_epsel_p1_000
tag @s remove dlg_epsel_p1_100
tag @s remove dlg_epsel_p1_210
tag @s remove dlg_epsel_p1_221
tag @s remove dlg_epsel_p1_222
tag @s remove dlg_epsel_p2_111
tag @s remove dlg_start_700
tag @s remove dlg_start_800
tag @s remove dlg_start_900
tag @s remove dlg_deny_700
tag @s remove dlg_deny_800
tag @s remove dlg_deny_900
tag @s remove dlg_epsel_p2_000
tag @s remove dlg_epsel_p2_100
tag @s remove dlg_epsel_p2_210
tag @s remove dlg_epsel_p2_221
tag @s remove dlg_epsel_p2_222
tag @s remove dlg_manage_char_0
tag @s remove dlg_manage_char_1
tag @s remove dlg_manage_char_2
tag @s remove dlg_manage_char_3
tag @s remove dlg_manage_char_4
tag @s remove dlg_manage_char_5
tag @s remove dlg_manage_char_6
tag @s remove dlg_manage_char_7
tag @s remove dlg_manage_char_8
tag @s remove dlg_manage_char_9
tag @s remove dlg_view_perks_0
tag @s remove dlg_view_perks_1
tag @s remove dlg_view_perks_2
tag @s remove dlg_view_perks_3
tag @s remove dlg_view_perks_4
tag @s remove dlg_view_perks_5
tag @s remove dlg_view_perks_6
tag @s remove dlg_view_perks_7
tag @s remove dlg_view_perks_8
tag @s remove dlg_view_perks_9
tag @s remove dlg_new_player
tag @s remove dlg_new_session
tag @s remove dlg_new_session_with_exit
tag @s remove dlg_settings
tag @s remove dlg_settings_ingame
tag @s remove dlg_settings_ingame_confirm
tag @s remove dlg_settings_music_is_1
tag @s remove dlg_settings_music_is_0
tag @s remove dlg_settings_sfx_is_1
tag @s remove dlg_settings_sfx_is_0
tag @s remove dlg_settings_perf_is_1
tag @s remove dlg_settings_perf_is_0
tag @s remove dlg_settings_perf_info
tag @s remove dlg_settings_streamer_is_1
tag @s remove dlg_settings_streamer_is_0
tag @s remove dlg_squad_recall
tag @s remove dlg_squad_info
tag @s remove dlg_squad_unavailable
tag @s remove dlg_squad_return
tag @s remove dlg_squad_ai_is_0
tag @s remove dlg_squad_ai_is_1
tag @s remove dlg_oobe_welcome
tag @s remove dlg_oobe_age
tag @s remove dlg_oobe_review_pc_0
tag @s remove dlg_oobe_review_pc_1
tag @s remove dlg_oobe_review_console_0
tag @s remove dlg_oobe_review_console_1
tag @s remove dlg_oobe_review_mobile_0
tag @s remove dlg_oobe_review_mobile_1
tag @s remove dlg_oobe_review_nx_0
tag @s remove dlg_oobe_review_nx_1
tag @s remove dlg_close_ui_player_0
tag @s remove dlg_close_ui_player_1
tag @s remove dlg_close_ui_player_2
tag @s remove dlg_close_ui_player_3
tag @s remove dlg_debug_left_large
tag @s remove dlg_debug_left
tag @s remove dlg_dlgsys_1
tag @s remove dlg_unreachable
tag @s remove dlg_rocksteady_intro
tag @s remove dlg_big_boss
tag @s remove dlg_rocksteady_testing
tag @s remove dlg_rocksteady_error
tag @s remove dlg_april_nothing_new
tag @s remove dlg_april_outside_weird_pizza
tag @s remove dlg_april_outside_weird_pizza_1
tag @s remove dlg_april_outside_weird_pizza_2
tag @s remove dlg_april_post_shredder
tag @s remove dlg_april_path_good_0
tag @s remove dlg_april_path_good_1
tag @s remove dlg_april_path_good_2
tag @s remove dlg_april_path_bad_0
tag @s remove dlg_april_path_bad_1
tag @s remove dlg_april_path_bad_2
tag @s remove dlg_bebop_breaks_ladder
tag @s remove dlg_bebop_far_enough
tag @s remove dlg_bebop_not_so_fast
tag @s remove dlg_bebop_not_so_fast_1
tag @s remove dlg_bebop_takes_pizza_0
tag @s remove dlg_bebop_takes_pizza_1
tag @s remove dlg_rocksteady_get_through_me
tag @s remove dlg_rocksteady_get_through_me_1
tag @s remove dlg_rocksteady_taunt_0
tag @s remove dlg_rocksteady_taunt_1
tag @s remove dlg_rocksteady_train_0
tag @s remove dlg_rocksteady_train_1
tag @s remove dlg_rocksteady_train_2
tag @s remove dlg_rocksteady_where_is_bebop
tag @s remove dlg_shredder_portal_worked
tag @s remove dlg_shredder_portal_worked_1
tag @s remove dlg_shredder_uses_portal_device
tag @s remove dlg_shredder_uses_portal_device_1
tag @s remove dlg_shredder_uses_portal_device_2
tag @s remove dlg_splinter_final_fight
tag @s remove dlg_splinter_final_fight_1
tag @s remove dlg_splinter_inspo_1
tag @s remove dlg_splinter_inspo_2
tag @s remove dlg_splinter_inspo_3
tag @s remove dlg_splinter_inspo_4
tag @s remove dlg_splinter_deny_play
tag @s remove dlg_splinter_onboarding_1
tag @s remove dlg_splinter_onboarding_2
tag @s remove dlg_splinter_onboarding_3
tag @s remove dlg_splinter_onboarding_3_confirm
tag @s remove dlg_splinter_onboarding_4
tag @s remove dlg_splinter_onboarding_p2_1
tag @s remove dlg_post_fight_rocksteady
tag @s remove dlg_post_fight_rocksteady_1
tag @s remove dlg_post_fight_rocksteady_2
tag @s remove dlg_post_fight_rocksteady_3
tag @s remove dlg_post_fight_shredder
tag @s remove dlg_post_fight_shredder_1
tag @s remove dlg_post_fight_super_shredder
tag @s remove dlg_post_fight_super_shredder_1
tag @s remove dlg_pre_fight_baxter_stockman
tag @s remove dlg_pre_fight_baxter_stockman_1
tag @s remove dlg_pre_fight_bebop
tag @s remove dlg_pre_fight_bebop_1
tag @s remove dlg_krang_pre_fight
tag @s remove dlg_krang_pre_fight_1
tag @s remove dlg_leatherhead_pre_fight
tag @s remove dlg_leatherhead_pre_fight_1
tag @s remove dlg_pre_fight_rocksteady
tag @s remove dlg_pre_fight_rocksteady_1
tag @s remove dlg_pre_fight_shredder
tag @s remove dlg_pre_fight_shredder_1
tag @s remove dlg_super_krang_pre_fight
tag @s remove dlg_super_krang_pre_fight_1
tag @s remove dlg_super_shredder_pre_fight
tag @s remove dlg_super_shredder_pre_fight_1
tag @s remove dlg_tempestra_pre_fight
tag @s remove dlg_tempestra_pre_fight_1
tag @s remove dlg_tcom_0001
tag @s remove dlg_tcom_0999
tag @s remove dlg_tcom_0090
tag @s remove dlg_tcom_0091
tag @s remove dlg_tcom_0050
tag @s remove dlg_tcom_0051
tag @s remove dlg_tcom_0052
tag @s remove dlg_tcom_0469
tag @s remove dlg_tcom_0470
tag @s remove dlg_tcom_0669
tag @s remove dlg_tcom_0670
tag @s remove dlg_tcom_0100
tag @s remove dlg_tcom_0101
tag @s remove dlg_tcom_0103
tag @s remove dlg_tcom_0104
tag @s remove dlg_tcom_5010
tag @s remove dlg_tcom_5012
tag @s remove dlg_tcom_0002
tag @s remove dlg_tcom_0003
tag @s remove dlg_tcom_0004
tag @s remove dlg_tcom_0005
tag @s remove dlg_tcom_0006
tag @s remove dlg_tcom_0007
tag @s remove dlg_tcom_2000
tag @s remove dlg_tcom_2001
tag @s remove dlg_tcom_2002
tag @s remove dlg_tcom_0300
tag @s remove dlg_tcom_0301
tag @s remove dlg_tcom_3030
tag @s remove dlg_tcom_3031
tag @s remove dlg_tcom_3032
tag @s remove dlg_tcom_0302
tag @s remove dlg_tcom_0303
tag @s remove dlg_tcom_0304