tag @e remove particle_enemy_appear
tag @e remove particle_enemy_death
tag @e remove particle_enemy_land
tag @e remove particle_power_attack_don
tag @e remove particle_power_attack_leo
tag @e remove particle_power_attack_mikey
tag @e remove particle_power_attack_raph
tag @e remove particle_projectile_hit
tag @e remove particle_weapon_hit
tag @e remove particle_smoke
tag @e remove particle_dust