## @(com.57digital.shulker.generated)
## Origin: C:\Users\Luke\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_behavior_packs\PP_BP\_project\lib\soundParser.js
stopsound @a fs.music.music_boss_baxter_stockman_loop
stopsound @a fs.music.music_boss_bebop_loop
stopsound @a fs.music.music_boss_krang_loop
stopsound @a fs.music.music_boss_leatherhead_loop
stopsound @a fs.music.music_boss_rocksteady_loop
stopsound @a fs.music.music_boss_shredder_loop
stopsound @a fs.music.music_boss_super_krang_loop
stopsound @a fs.music.music_boss_super_shredder_loop
stopsound @a fs.music.music_boss_tempestra_loop
stopsound @a fs.music.music_dlg_0_loop
stopsound @a fs.music.music_dlg_1_loop
stopsound @a fs.music.music_level_100_fight_loop
stopsound @a fs.music.music_level_100_normal_loop
stopsound @a fs.music.music_level_101_normal_loop
stopsound @a fs.music.music_level_200_fight_loop
stopsound @a fs.music.music_level_200_normal_loop
stopsound @a fs.music.music_level_300_fight_loop
stopsound @a fs.music.music_level_300_normal_loop
stopsound @a fs.music.music_level_400_fight_loop
stopsound @a fs.music.music_level_400_normal_loop
stopsound @a fs.music.music_level_500_fight_loop
stopsound @a fs.music.music_level_500_normal_loop
stopsound @a fs.music.music_level_50_normal_loop
stopsound @a fs.music.music_level_600_fight_loop
stopsound @a fs.music.music_level_600_normal_loop
stopsound @a fs.music.music_level_800_fight_loop
stopsound @a fs.music.music_level_800_normal_loop
stopsound @a fs.music.music_theme_loop