## Generated File - Do not modify
##!redact
tag @s remove nametag_fs:zone_sensor
tag @s remove nametag_minecraft:armor_stand
tag @s remove nametag_fs:ai_marker
tag @s remove nametag_fs:enemy_foot_soldier
tag @s remove nametag_fs:enemy_foot_soldier_black
tag @s remove nametag_fs:enemy_foot_soldier_blue
tag @s remove nametag_fs:enemy_foot_soldier_green
tag @s remove nametag_fs:enemy_foot_soldier_indigo
tag @s remove nametag_fs:enemy_foot_soldier_lime
tag @s remove nametag_fs:enemy_foot_soldier_orange
tag @s remove nametag_fs:enemy_foot_soldier_pink
tag @s remove nametag_fs:enemy_foot_soldier_white
tag @s remove nametag_fs:enemy_foot_soldier_yellow
tag @s remove nametag_fs:enemy_mouser
tag @s remove nametag_fs:enemy_pole_laser
tag @s remove nametag_fs:enemy_rat
tag @s remove nametag_fs:enemy_roadkill_rodney
tag @s remove nametag_fs:enemy_robot_walker
tag @s remove nametag_fs:enemy_rock_soldier
tag @s remove nametag_fs:enemy_rock_soldier_gray
tag @s remove nametag_fs:enemy_surfing_mine
tag @s remove nametag_fs:enemy_triceraton
tag @s remove nametag_fs:enemy_triceraton_orange
tag @s remove nametag_fs:enemy_wall_laser
tag @s remove nametag_fs:effect_portal
tag @s remove nametag_fs:interact_breaker_switch
tag @s remove nametag_fs:interact_button_emergency
tag @s remove nametag_fs:interact_button_general
tag @s remove nametag_fs:interact_button_lift
tag @s remove nametag_fs:interact_padlock
tag @s remove nametag_fs:sticker_graffiti_floor_0
tag @s remove nametag_fs:sticker_graffiti_floor_foot_left
tag @s remove nametag_fs:sticker_graffiti_floor_foot_right
tag @s remove nametag_fs:sticker_graffiti_wall_0
tag @s remove nametag_fs:sticker_graffiti_wall_1
tag @s remove nametag_fs:sticker_graffiti_wall_2
tag @s remove nametag_fs:sticker_graffiti_wall_3
tag @s remove nametag_fs:sticker_graffiti_wall_4
tag @s remove nametag_fs:npc_ui_close
tag @s remove nametag_fs:npc_vernon
tag @s remove nametag_fs:npc_april_oneil
tag @s remove nametag_fs:npc_casey_jones
tag @s remove nametag_fs:npc_donatello
tag @s remove nametag_fs:npc_leonardo
tag @s remove nametag_fs:npc_michelangelo
tag @s remove nametag_fs:npc_raphael
tag @s remove nametag_fs:npc_splinter
tag @s remove nametag_fs:boss_baxter_stockman
tag @s remove nametag_fs:boss_bebop
tag @s remove nametag_fs:boss_krang
tag @s remove nametag_fs:boss_leatherhead
tag @s remove nametag_fs:boss_rocksteady
tag @s remove nametag_fs:boss_shredder
tag @s remove nametag_fs:boss_super_krang
tag @s remove nametag_fs:boss_super_shredder
tag @s remove nametag_fs:boss_tempestra
tag @s remove nametag_fs:vehicle_channel_six_van
tag @s remove nametag_fs:vehicle_sewer_surfboard
tag @s remove nametag_fs:vehicle_skateboard
tag @s remove nametag_fs:vehicle_transport_module
tag @s remove nametag_fs:vehicle_van
tag @s remove nametag_fs:prop_armchair
tag @s remove nametag_fs:prop_bedroom_don
tag @s remove nametag_fs:prop_bedroom_leo
tag @s remove nametag_fs:prop_bedroom_mikey
tag @s remove nametag_fs:prop_bedroom_raph
tag @s remove nametag_fs:prop_bonsai_tree
tag @s remove nametag_fs:prop_desk_large
tag @s remove nametag_fs:prop_desk_small
tag @s remove nametag_fs:prop_don_lab_ceiling_laser
tag @s remove nametag_fs:prop_don_lab_desk
tag @s remove nametag_fs:prop_don_lab_machine
tag @s remove nametag_fs:prop_don_lab_workbench
tag @s remove nametag_fs:prop_exit_sign
tag @s remove nametag_fs:prop_floor_lamp
tag @s remove nametag_fs:prop_japanese_sign
tag @s remove nametag_fs:prop_kitchen_oven
tag @s remove nametag_fs:prop_kitchen_table
tag @s remove nametag_fs:prop_kitchen_unit
tag @s remove nametag_fs:prop_kitchen_unit_microwave
tag @s remove nametag_fs:prop_kitchen_unit_sink
tag @s remove nametag_fs:prop_kitchen_wall_unit
tag @s remove nametag_fs:prop_mirror
tag @s remove nametag_fs:prop_museum_armor
tag @s remove nametag_fs:prop_museum_skull
tag @s remove nametag_fs:prop_museum_sword
tag @s remove nametag_fs:prop_museum_vase
tag @s remove nametag_fs:prop_one_way_sign
tag @s remove nametag_fs:prop_photocopier
tag @s remove nametag_fs:prop_picture_beast
tag @s remove nametag_fs:prop_shoji_lamp
tag @s remove nametag_fs:prop_shoji_screen
tag @s remove nametag_fs:prop_tempestra_machine
tag @s remove nametag_fs:prop_turtle_rug
tag @s remove nametag_fs:prop_vending_machine_drinks
tag @s remove nametag_fs:prop_vending_machine_snacks
tag @s remove nametag_fs:prop_alley_bin
tag @s remove nametag_fs:prop_arcade_machine
tag @s remove nametag_fs:prop_barrier
tag @s remove nametag_fs:prop_boombox
tag @s remove nametag_fs:prop_coffee_table
tag @s remove nametag_fs:prop_crate
tag @s remove nametag_fs:prop_dumpster
tag @s remove nametag_fs:prop_exploding_barrel
tag @s remove nametag_fs:prop_fire_hydrant
tag @s remove nametag_fs:prop_foot_soldier_dummy
tag @s remove nametag_fs:prop_hot_dog_cart
tag @s remove nametag_fs:prop_mail_box
tag @s remove nametag_fs:prop_manhole_cover
tag @s remove nametag_fs:prop_park_bench
tag @s remove nametag_fs:prop_park_chess_table
tag @s remove nametag_fs:prop_parking_meter
tag @s remove nametag_fs:prop_pinball_machine
tag @s remove nametag_fs:prop_pizza_box
tag @s remove nametag_fs:prop_research_board
tag @s remove nametag_fs:prop_roadwork_sign
tag @s remove nametag_fs:prop_sofa
tag @s remove nametag_fs:prop_steam_vent
tag @s remove nametag_fs:prop_stop_sign
tag @s remove nametag_fs:prop_street_bin
tag @s remove nametag_fs:prop_subway_sign
tag @s remove nametag_fs:prop_traffic_barrier
tag @s remove nametag_fs:prop_traffic_cone
tag @s remove nametag_fs:prop_traffic_cone_large
tag @s remove nametag_fs:prop_tripod_camera
tag @s remove nametag_fs:prop_tv
tag @s remove nametag_fs:prop_video_madness_sign_arcade
tag @s remove nametag_fs:prop_video_madness_sign_logo
tag @s remove nametag_fs:prop_video_madness_sign_number
tag @s remove nametag_fs:prop_weird_pizza_sign_logo
tag @s remove nametag_fs:prop_weird_pizza_sign_pizza
tag @s remove nametag_fs:prop_weird_pizza_sign_weird
tag @s remove nametag_fs:portal_device
tag @s remove nametag_fs:portal_device_antenna
tag @s remove nametag_fs:portal_device_body
tag @s remove nametag_fs:portal_device_cpu
tag @s remove nametag_fs:portal_device_power
tag @s remove nametag_fs:item_pizza_extra_life
tag @s remove nametag_fs:item_pizza_extra_life
tag @s remove nametag_fs:item_pizza_health
tag @s remove nametag_fs:item_pizza_health
tag @s remove nametag_fs:item_pizza_ooze_attack
tag @s remove nametag_fs:item_pizza_ooze_attack
tag @s remove nametag_fs:gui_compass
tag @s remove nametag_fs:gui_go
tag @s remove nametag_fs:gui_icon_museum_armor
tag @s remove nametag_fs:gui_icon_museum_skull
tag @s remove nametag_fs:gui_icon_museum_sword
tag @s remove nametag_fs:gui_icon_museum_vase
tag @s remove nametag_fs:gui_path
tag @s remove nametag_fs:path_goal
tag @s remove nametag_fs:path_goal_trigger
tag @s remove nametag_fs:path_node
tag @s remove nametag_fs:wave_barrier
tag @s remove nametag_fs:wave_manager
tag @s remove nametag_fs:wave_spawner
tag @s remove nametag_fs:quest_item
tag @s remove nametag_fs:quest_item_handle
tag @s remove nametag_fs:quest_item_valve
tag @s remove nametag_fs:quest_manager
tag @s remove nametag_fs:zone_interactable
tag @s remove nametag_fs:zone_event
tag @s remove nametag_fs:trigger_block
tag @s remove nametag_fs:trigger_fight
tag @s remove nametag_fs:trigger_proximity
tag @s remove nametag_fs:zone_waypoint
tag @s remove nametag_fs:zone_sensor
tag @s remove nametag_minecraft:armor_stand