## @(com.57digital.shulker.generated)
stopsound @s fs.boss.b_bebop_damage_1
stopsound @s fs.boss.b_bebop_die_1
stopsound @s fs.boss.b_bebop_dlg_1
stopsound @s fs.boss.b_krang_damage_1
stopsound @s fs.boss.b_krang_die_1
stopsound @s fs.boss.b_krang_dlg_1
stopsound @s fs.boss.b_rocksteady_damage_1
stopsound @s fs.boss.b_rocksteady_die_1
stopsound @s fs.boss.b_rocksteady_dlg_1
stopsound @s fs.boss.b_shredder_damage_1
stopsound @s fs.boss.b_shredder_die_1
stopsound @s fs.boss.b_shredder_dlg_neg_1
stopsound @s fs.boss.b_shredder_dlg_pos_1
stopsound @s fs.boss.b_s_krang_damage_1
stopsound @s fs.boss.b_s_krang_die_1
stopsound @s fs.boss.b_s_krang_dlg_1
stopsound @s fs.boss.b_s_shredder_damage_1
stopsound @s fs.boss.b_s_shredder_die_1
stopsound @s fs.boss.b_s_shredder_dlg_neg_1
stopsound @s fs.boss.b_s_shredder_dlg_pos_1
stopsound @s fs.boss.b_baxter_damage_1
stopsound @s fs.boss.b_baxter_die_1
stopsound @s fs.boss.b_baxter_dlg_1
stopsound @s fs.boss.b_leather_die_1
stopsound @s fs.boss.b_leather_dlg_1
stopsound @s fs.boss.b_tempestra_damage_1
stopsound @s fs.boss.b_tempestra_die_1
stopsound @s fs.boss.b_tempestra_dlg_1
stopsound @s fs.boss.b_leather_damage_1
stopsound @s fs.boss.b_krang_ranged_1
stopsound @s fs.boss.b_krang_spin_1