## @(com.57digital.shulker.generated)
stopsound @s fs.sfx.placeholder_letskickshell
stopsound @s fs.sfx.placeholder_don_select
stopsound @s fs.sfx.placeholder_leo_select
stopsound @s fs.sfx.placeholder_mich_select
stopsound @s fs.sfx.placeholder_raph_select
stopsound @s fs.sfx.placeholder_april
stopsound @s fs.sfx.placeholder_splinter
stopsound @s fs.sfx.placeholder_splinter_areyousure
stopsound @s fs.sfx.placeholder_bebop_sayprayer
stopsound @s fs.sfx.placeholder_bebop_whatthe
stopsound @s fs.sfx.placeholder_theme_jungle
stopsound @s fs.sfx.placeholder_bebop_snort
stopsound @s fs.sfx.placeholder_fight_end
stopsound @s fs.sfx.placeholder_fight_start
stopsound @s fs.sfx.placeholder_explosion
stopsound @s fs.sfx.placeholder_dash
stopsound @s fs.sfx.placeholder_jump
stopsound @s fs.sfx.placeholder_jump_vo
stopsound @s fs.sfx.silent
stopsound @s fs.sfx.elevator_call
stopsound @s fs.sfx.quest_electric_switch
stopsound @s fs.sfx.training_goal_complete
stopsound @s fs.sfx.training_gong
stopsound @s fs.sfx.training_start
stopsound @s fs.sfx.party_wagon_tuning
stopsound @s fs.sfx.lights_out
stopsound @s fs.sfx.glass_smash
stopsound @s fs.sfx.compass_checkpoint
stopsound @s fs.sfx.leo_attack_0
stopsound @s fs.sfx.leo_attack_1
stopsound @s fs.sfx.leo_attack_2
stopsound @s fs.sfx.leo_attack_5
stopsound @s fs.sfx.leo_hurt_0
stopsound @s fs.sfx.leo_hurt_1
stopsound @s fs.sfx.leo_jump_1
stopsound @s fs.sfx.leo_jump_3
stopsound @s fs.sfx.leo_super_0
stopsound @s fs.sfx.leo_throw_0
stopsound @s fs.sfx.chain_break
stopsound @s fs.sfx.quest_btn_press
stopsound @s fs.sfx.super_attack_demo
stopsound @s fs.sfx.no_objectives
stopsound @s fs.sfx.pizza_1up
stopsound @s fs.sfx.pizza_hp
stopsound @s fs.sfx.arcade_block
stopsound @s fs.sfx.arcade_blocked
stopsound @s fs.sfx.arcade_coin
stopsound @s fs.sfx.arcade_fire_hit
stopsound @s fs.sfx.arcade_ice_hit
stopsound @s fs.sfx.arcade_jump
stopsound @s fs.sfx.arcade_reset
stopsound @s fs.sfx.arcade_rock_hit
stopsound @s fs.sfx.arcade_teleport
stopsound @s fs.sfx.arcade_game_over
stopsound @s fs.sfx.arcade_game_start
stopsound @s fs.sfx.wrong_code
stopsound @s fs.sfx.super_don_3
stopsound @s fs.sfx.super_don_4
stopsound @s fs.sfx.super_don_5
stopsound @s fs.sfx.super_don_6
stopsound @s fs.sfx.super_leo_3
stopsound @s fs.sfx.super_leo_4
stopsound @s fs.sfx.super_leo_5
stopsound @s fs.sfx.super_leo_6
stopsound @s fs.sfx.super_mich_3
stopsound @s fs.sfx.super_mich_4
stopsound @s fs.sfx.super_mich_5
stopsound @s fs.sfx.super_mich_6
stopsound @s fs.sfx.super_raph_3
stopsound @s fs.sfx.super_raph_4
stopsound @s fs.sfx.super_raph_5
stopsound @s fs.sfx.super_raph_6
stopsound @s fs.sfx.got_quest_item
stopsound @s fs.sfx.ooze_hit
stopsound @s fs.sfx.ooze_ready
stopsound @s fs.sfx.pizza_heal
stopsound @s fs.sfx.splinter_dlg_1
stopsound @s fs.sfx.access_granted
stopsound @s fs.sfx.code_enter
stopsound @s fs.sfx.low_health
stopsound @s fs.sfx.critical_health