## @(com.57digital.shulker.generated)
stopsound @s fs.dlg.open
stopsound @s fs.dlg.btn
stopsound @s fs.sfx.placeholder_letskickshell
stopsound @s fs.sfx.placeholder_don_select
stopsound @s fs.sfx.placeholder_leo_select
stopsound @s fs.sfx.placeholder_mich_select
stopsound @s fs.sfx.placeholder_raph_select
stopsound @s fs.sfx.placeholder_april
stopsound @s fs.sfx.placeholder_splinter
stopsound @s fs.sfx.placeholder_splinter_areyousure
stopsound @s fs.sfx.placeholder_bebop_sayprayer
stopsound @s fs.sfx.placeholder_bebop_whatthe
stopsound @s fs.sfx.placeholder_theme_jungle
stopsound @s fs.sfx.placeholder_bebop_snort
stopsound @s fs.sfx.placeholder_fight_end
stopsound @s fs.sfx.placeholder_fight_start
stopsound @s fs.sfx.placeholder_explosion
stopsound @s fs.music.music_theme_loop
stopsound @s fs.sfx.placeholder_dash
stopsound @s fs.sfx.placeholder_jump
stopsound @s fs.sfx.placeholder_jump_vo
stopsound @s fs.dlg.ep_select
stopsound @s fs.dlg.nav
stopsound @s fs.music.music_dlg_0_loop
stopsound @s fs.music.music_dlg_1_loop
stopsound @s fs.ui.toast
stopsound @s fs.music.music_level_100_fight_loop
stopsound @s fs.music.music_level_100_normal_loop
stopsound @s fs.music.music_level_600_fight_loop
stopsound @s fs.music.music_level_600_normal_loop
stopsound @s fs.music.music_level_500_normal_loop
stopsound @s fs.music.music_level_50_normal_loop
stopsound @s fs.dlg.tcom_open
stopsound @s fs.music.music_level_200_fight_loop
stopsound @s fs.music.music_level_200_normal_loop
stopsound @s fs.music.music_level_300_fight_loop
stopsound @s fs.music.music_level_300_normal_loop
stopsound @s fs.music.music_level_400_fight_loop
stopsound @s fs.music.music_level_400_normal_loop
stopsound @s fs.music.music_level_500_fight_loop
stopsound @s fs.ui.objective_complete
stopsound @s fs.ui.objective_new
stopsound @s fs.ui.deny_level
stopsound @s fs.music.music_boss_bebop_loop
stopsound @s fs.music.music_level_800_fight_loop
stopsound @s fs.music.music_level_800_normal_loop
stopsound @s fs.sfx.silent
stopsound @s fs.sfx.elevator_call
stopsound @s fs.sfx.quest_electric_switch
stopsound @s fs.music.music_boss_krang_loop
stopsound @s fs.music.music_boss_shredder_loop
stopsound @s fs.music.music_boss_baxter_stockman_loop
stopsound @s fs.music.music_boss_super_krang_loop
stopsound @s fs.music.music_boss_super_shredder_loop
stopsound @s fs.music.music_boss_tempestra_loop
stopsound @s fs.music.music_boss_rocksteady_loop
stopsound @s fs.music.music_boss_leatherhead_loop
stopsound @s fs.sfx.training_goal_complete
stopsound @s fs.sfx.training_gong
stopsound @s fs.sfx.training_start
stopsound @s fs.sfx.party_wagon_tuning
stopsound @s fs.stings.sting_boss_intro
stopsound @s fs.stings.sting_boss_outro
stopsound @s fs.stings.sting_death
stopsound @s fs.stings.sting_fight1
stopsound @s fs.stings.sting_fight2
stopsound @s fs.stings.sting_fight3
stopsound @s fs.stings.sting_fight4
stopsound @s fs.stings.sting_fight5
stopsound @s fs.stings.sting_fight6
stopsound @s fs.stings.sting_level_up
stopsound @s fs.stings.sting_new_objective
stopsound @s fs.stings.sting_notification
stopsound @s fs.stings.sting_objective_complete
stopsound @s fs.stings.sting_revive
stopsound @s fs.sfx.lights_out
stopsound @s fs.music.music_level_101_normal_loop
stopsound @s fs.sfx.glass_smash
stopsound @s fs.ui.chat_msg
stopsound @s fs.ui.chat_hint
stopsound @s fs.sfx.compass_checkpoint
stopsound @s fs.sfx.leo_attack_0
stopsound @s fs.sfx.leo_attack_1
stopsound @s fs.sfx.leo_attack_2
stopsound @s fs.sfx.leo_attack_5
stopsound @s fs.sfx.leo_hurt_0
stopsound @s fs.sfx.leo_hurt_1
stopsound @s fs.sfx.leo_jump_1
stopsound @s fs.sfx.leo_jump_3
stopsound @s fs.sfx.leo_super_0
stopsound @s fs.sfx.leo_throw_0
stopsound @s fs.sfx.chain_break
stopsound @s fs.sfx.quest_btn_press
stopsound @s fs.sfx.super_attack_demo
stopsound @s fs.sfx.no_objectives
stopsound @s fs.sfx.pizza_1up
stopsound @s fs.sfx.pizza_hp
stopsound @s fs.weapon.hit_dagger_4
stopsound @s fs.weapon.hit_staff_3
stopsound @s fs.weapon.hit_staff_4
stopsound @s fs.weapon.swing_dagger_1
stopsound @s fs.weapon.swing_dagger_2
stopsound @s fs.weapon.swing_dagger_3
stopsound @s fs.weapon.swing_nunchuk_1
stopsound @s fs.weapon.swing_nunchuk_2
stopsound @s fs.weapon.swing_nunchuk_3
stopsound @s fs.weapon.swing_nunchuk_4
stopsound @s fs.weapon.swing_staff_1
stopsound @s fs.weapon.swing_staff_2
stopsound @s fs.weapon.swing_whoosh_1
stopsound @s fs.weapon.swing_whoosh_2
stopsound @s fs.weapon.swing_whoosh_3
stopsound @s fs.weapon.swing_whoosh_4
stopsound @s fs.weapon.hit_ninjastar_0
stopsound @s fs.weapon.throw_ninjastar_0
stopsound @s fs.weapon.throw_ninjastar_1
stopsound @s fs.weapon.throw_ninjastar_2
stopsound @s fs.weapon.hit_ninjastar_1
stopsound @s fs.ui.chat_msg_delay1s
stopsound @s fs.sfx.arcade_block
stopsound @s fs.sfx.arcade_blocked
stopsound @s fs.sfx.arcade_coin
stopsound @s fs.sfx.arcade_fire_hit
stopsound @s fs.sfx.arcade_ice_hit
stopsound @s fs.sfx.arcade_jump
stopsound @s fs.sfx.arcade_reset
stopsound @s fs.sfx.arcade_rock_hit
stopsound @s fs.sfx.arcade_teleport
stopsound @s fs.sfx.arcade_game_over
stopsound @s fs.sfx.arcade_game_start
stopsound @s fs.sfx.wrong_code
stopsound @s fs.sfx.super_don_3
stopsound @s fs.sfx.super_don_4
stopsound @s fs.sfx.super_don_5
stopsound @s fs.sfx.super_don_6
stopsound @s fs.sfx.super_leo_3
stopsound @s fs.sfx.super_leo_4
stopsound @s fs.sfx.super_leo_5
stopsound @s fs.sfx.super_leo_6
stopsound @s fs.sfx.super_mich_3
stopsound @s fs.sfx.super_mich_4
stopsound @s fs.sfx.super_mich_5
stopsound @s fs.sfx.super_mich_6
stopsound @s fs.sfx.super_raph_3
stopsound @s fs.sfx.super_raph_4
stopsound @s fs.sfx.super_raph_5
stopsound @s fs.sfx.super_raph_6
stopsound @s fs.sfx.got_quest_item
stopsound @s fs.sfx.ooze_hit
stopsound @s fs.sfx.ooze_ready
stopsound @s fs.sfx.pizza_heal
stopsound @s fs.boss.b_bebop_damage_1
stopsound @s fs.boss.b_bebop_die_1
stopsound @s fs.boss.b_bebop_dlg_1
stopsound @s fs.boss.b_krang_damage_1
stopsound @s fs.boss.b_krang_die_1
stopsound @s fs.boss.b_krang_dlg_1
stopsound @s fs.boss.b_rocksteady_damage_1
stopsound @s fs.boss.b_rocksteady_die_1
stopsound @s fs.boss.b_rocksteady_dlg_1
stopsound @s fs.boss.b_shredder_damage_1
stopsound @s fs.boss.b_shredder_die_1
stopsound @s fs.boss.b_shredder_dlg_neg_1
stopsound @s fs.boss.b_shredder_dlg_pos_1
stopsound @s fs.boss.b_s_krang_damage_1
stopsound @s fs.boss.b_s_krang_die_1
stopsound @s fs.boss.b_s_krang_dlg_1
stopsound @s fs.boss.b_s_shredder_damage_1
stopsound @s fs.boss.b_s_shredder_die_1
stopsound @s fs.boss.b_s_shredder_dlg_neg_1
stopsound @s fs.boss.b_s_shredder_dlg_pos_1
stopsound @s fs.sfx.splinter_dlg_1
stopsound @s fs.boss.b_baxter_damage_1
stopsound @s fs.boss.b_baxter_die_1
stopsound @s fs.boss.b_baxter_dlg_1
stopsound @s fs.boss.b_leather_die_1
stopsound @s fs.boss.b_leather_dlg_1
stopsound @s fs.boss.b_tempestra_damage_1
stopsound @s fs.boss.b_tempestra_die_1
stopsound @s fs.boss.b_tempestra_dlg_1
stopsound @s fs.sfx.access_granted
stopsound @s fs.sfx.code_enter
stopsound @s fs.sfx.low_health
stopsound @s fs.boss.b_leather_damage_1
stopsound @s fs.sfx.critical_health
stopsound @s fs.boss.b_krang_ranged_1
stopsound @s fs.boss.b_krang_spin_1