execute as @s[scores={level=50}] run function music/play/music_level_50_normal_loop
execute as @s[scores={level=100..199}] run function music/play/music_level_100_fight_loop
execute as @s[scores={level=200..299}] run function music/play/music_level_200_fight_loop
execute as @s[scores={level=300..399}] run function music/play/music_level_300_fight_loop
execute as @s[scores={level=400..499}] run function music/play/music_level_400_fight_loop
execute as @s[scores={level=500..599}] run function music/play/music_level_500_fight_loop
execute as @s[scores={level=600..699}] run function music/play/music_level_600_fight_loop
execute as @s[scores={level=700..799}] run function music/play/music_level_100_fight_loop
execute as @s[scores={level=800..899}] run function music/play/music_level_800_fight_loop
execute as @s[scores={level=900..999}] run function music/play/music_level_100_fight_loop